// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorldSkillsSmartUniversityApi.Models.Domain;

namespace WorldSkillsSmartUniversityApi.Migrations
{
    [DbContext(typeof(SmartUniversityDbContext))]
    [Migration("20190430193944_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034");

            modelBuilder.Entity("WorldSkillsSmartUniversityApi.Models.Domain.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("RoomId");

                    b.Property<int>("Type");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("Devices");

                    b.HasData(
                        new
                        {
                            Id = -4,
                            Name = "Люстра",
                            RoomId = -1,
                            Type = 1,
                            UserId = "ws1",
                            Value = "off"
                        },
                        new
                        {
                            Id = -3,
                            Name = "Окно",
                            RoomId = -1,
                            Type = 4,
                            UserId = "ws1",
                            Value = "closed"
                        },
                        new
                        {
                            Id = -2,
                            Name = "Кондиционер",
                            RoomId = -1,
                            Type = 3,
                            UserId = "ws1",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -1,
                            Name = "Датчик температуры",
                            RoomId = -1,
                            Type = 6,
                            UserId = "ws1",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -9,
                            Name = "Люстра",
                            RoomId = -2,
                            Type = 1,
                            UserId = "ws2",
                            Value = "off"
                        },
                        new
                        {
                            Id = -8,
                            Name = "Окно",
                            RoomId = -2,
                            Type = 4,
                            UserId = "ws2",
                            Value = "closed"
                        },
                        new
                        {
                            Id = -7,
                            Name = "Кондиционер",
                            RoomId = -2,
                            Type = 3,
                            UserId = "ws2",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -6,
                            Name = "Датчик температуры",
                            RoomId = -2,
                            Type = 6,
                            UserId = "ws2",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -14,
                            Name = "Люстра",
                            RoomId = -3,
                            Type = 1,
                            UserId = "ws3",
                            Value = "off"
                        },
                        new
                        {
                            Id = -13,
                            Name = "Окно",
                            RoomId = -3,
                            Type = 4,
                            UserId = "ws3",
                            Value = "closed"
                        },
                        new
                        {
                            Id = -12,
                            Name = "Кондиционер",
                            RoomId = -3,
                            Type = 3,
                            UserId = "ws3",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -11,
                            Name = "Датчик температуры",
                            RoomId = -3,
                            Type = 6,
                            UserId = "ws3",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -19,
                            Name = "Люстра",
                            RoomId = -4,
                            Type = 1,
                            UserId = "ws4",
                            Value = "off"
                        },
                        new
                        {
                            Id = -18,
                            Name = "Окно",
                            RoomId = -4,
                            Type = 4,
                            UserId = "ws4",
                            Value = "closed"
                        },
                        new
                        {
                            Id = -17,
                            Name = "Кондиционер",
                            RoomId = -4,
                            Type = 3,
                            UserId = "ws4",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -16,
                            Name = "Датчик температуры",
                            RoomId = -4,
                            Type = 6,
                            UserId = "ws4",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -24,
                            Name = "Люстра",
                            RoomId = -5,
                            Type = 1,
                            UserId = "ws5",
                            Value = "off"
                        },
                        new
                        {
                            Id = -23,
                            Name = "Окно",
                            RoomId = -5,
                            Type = 4,
                            UserId = "ws5",
                            Value = "closed"
                        },
                        new
                        {
                            Id = -22,
                            Name = "Кондиционер",
                            RoomId = -5,
                            Type = 3,
                            UserId = "ws5",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -21,
                            Name = "Датчик температуры",
                            RoomId = -5,
                            Type = 6,
                            UserId = "ws5",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -29,
                            Name = "Люстра",
                            RoomId = -6,
                            Type = 1,
                            UserId = "ws6",
                            Value = "off"
                        },
                        new
                        {
                            Id = -28,
                            Name = "Окно",
                            RoomId = -6,
                            Type = 4,
                            UserId = "ws6",
                            Value = "closed"
                        },
                        new
                        {
                            Id = -27,
                            Name = "Кондиционер",
                            RoomId = -6,
                            Type = 3,
                            UserId = "ws6",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -26,
                            Name = "Датчик температуры",
                            RoomId = -6,
                            Type = 6,
                            UserId = "ws6",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -34,
                            Name = "Люстра",
                            RoomId = -7,
                            Type = 1,
                            UserId = "ws7",
                            Value = "off"
                        },
                        new
                        {
                            Id = -33,
                            Name = "Окно",
                            RoomId = -7,
                            Type = 4,
                            UserId = "ws7",
                            Value = "closed"
                        },
                        new
                        {
                            Id = -32,
                            Name = "Кондиционер",
                            RoomId = -7,
                            Type = 3,
                            UserId = "ws7",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -31,
                            Name = "Датчик температуры",
                            RoomId = -7,
                            Type = 6,
                            UserId = "ws7",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -39,
                            Name = "Люстра",
                            RoomId = -8,
                            Type = 1,
                            UserId = "ws8",
                            Value = "off"
                        },
                        new
                        {
                            Id = -38,
                            Name = "Окно",
                            RoomId = -8,
                            Type = 4,
                            UserId = "ws8",
                            Value = "closed"
                        },
                        new
                        {
                            Id = -37,
                            Name = "Кондиционер",
                            RoomId = -8,
                            Type = 3,
                            UserId = "ws8",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -36,
                            Name = "Датчик температуры",
                            RoomId = -8,
                            Type = 6,
                            UserId = "ws8",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -44,
                            Name = "Люстра",
                            RoomId = -9,
                            Type = 1,
                            UserId = "ws9",
                            Value = "off"
                        },
                        new
                        {
                            Id = -43,
                            Name = "Окно",
                            RoomId = -9,
                            Type = 4,
                            UserId = "ws9",
                            Value = "closed"
                        },
                        new
                        {
                            Id = -42,
                            Name = "Кондиционер",
                            RoomId = -9,
                            Type = 3,
                            UserId = "ws9",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -41,
                            Name = "Датчик температуры",
                            RoomId = -9,
                            Type = 6,
                            UserId = "ws9",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -49,
                            Name = "Люстра",
                            RoomId = -10,
                            Type = 1,
                            UserId = "ws10",
                            Value = "off"
                        },
                        new
                        {
                            Id = -48,
                            Name = "Окно",
                            RoomId = -10,
                            Type = 4,
                            UserId = "ws10",
                            Value = "closed"
                        },
                        new
                        {
                            Id = -47,
                            Name = "Кондиционер",
                            RoomId = -10,
                            Type = 3,
                            UserId = "ws10",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -46,
                            Name = "Датчик температуры",
                            RoomId = -10,
                            Type = 6,
                            UserId = "ws10",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -54,
                            Name = "Люстра",
                            RoomId = -11,
                            Type = 1,
                            UserId = "ws11",
                            Value = "off"
                        },
                        new
                        {
                            Id = -53,
                            Name = "Окно",
                            RoomId = -11,
                            Type = 4,
                            UserId = "ws11",
                            Value = "closed"
                        },
                        new
                        {
                            Id = -52,
                            Name = "Кондиционер",
                            RoomId = -11,
                            Type = 3,
                            UserId = "ws11",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -51,
                            Name = "Датчик температуры",
                            RoomId = -11,
                            Type = 6,
                            UserId = "ws11",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -59,
                            Name = "Люстра",
                            RoomId = -12,
                            Type = 1,
                            UserId = "ws12",
                            Value = "off"
                        },
                        new
                        {
                            Id = -58,
                            Name = "Окно",
                            RoomId = -12,
                            Type = 4,
                            UserId = "ws12",
                            Value = "closed"
                        },
                        new
                        {
                            Id = -57,
                            Name = "Кондиционер",
                            RoomId = -12,
                            Type = 3,
                            UserId = "ws12",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -56,
                            Name = "Датчик температуры",
                            RoomId = -12,
                            Type = 6,
                            UserId = "ws12",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -64,
                            Name = "Люстра",
                            RoomId = -13,
                            Type = 1,
                            UserId = "ws13",
                            Value = "off"
                        },
                        new
                        {
                            Id = -63,
                            Name = "Окно",
                            RoomId = -13,
                            Type = 4,
                            UserId = "ws13",
                            Value = "closed"
                        },
                        new
                        {
                            Id = -62,
                            Name = "Кондиционер",
                            RoomId = -13,
                            Type = 3,
                            UserId = "ws13",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -61,
                            Name = "Датчик температуры",
                            RoomId = -13,
                            Type = 6,
                            UserId = "ws13",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -69,
                            Name = "Люстра",
                            RoomId = -14,
                            Type = 1,
                            UserId = "ws14",
                            Value = "off"
                        },
                        new
                        {
                            Id = -68,
                            Name = "Окно",
                            RoomId = -14,
                            Type = 4,
                            UserId = "ws14",
                            Value = "closed"
                        },
                        new
                        {
                            Id = -67,
                            Name = "Кондиционер",
                            RoomId = -14,
                            Type = 3,
                            UserId = "ws14",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -66,
                            Name = "Датчик температуры",
                            RoomId = -14,
                            Type = 6,
                            UserId = "ws14",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -74,
                            Name = "Люстра",
                            RoomId = -15,
                            Type = 1,
                            UserId = "ws15",
                            Value = "off"
                        },
                        new
                        {
                            Id = -73,
                            Name = "Окно",
                            RoomId = -15,
                            Type = 4,
                            UserId = "ws15",
                            Value = "closed"
                        },
                        new
                        {
                            Id = -72,
                            Name = "Кондиционер",
                            RoomId = -15,
                            Type = 3,
                            UserId = "ws15",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -71,
                            Name = "Датчик температуры",
                            RoomId = -15,
                            Type = 6,
                            UserId = "ws15",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -79,
                            Name = "Люстра",
                            RoomId = -16,
                            Type = 1,
                            UserId = "ws16",
                            Value = "off"
                        },
                        new
                        {
                            Id = -78,
                            Name = "Окно",
                            RoomId = -16,
                            Type = 4,
                            UserId = "ws16",
                            Value = "closed"
                        },
                        new
                        {
                            Id = -77,
                            Name = "Кондиционер",
                            RoomId = -16,
                            Type = 3,
                            UserId = "ws16",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -76,
                            Name = "Датчик температуры",
                            RoomId = -16,
                            Type = 6,
                            UserId = "ws16",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -84,
                            Name = "Люстра",
                            RoomId = -17,
                            Type = 1,
                            UserId = "ws17",
                            Value = "off"
                        },
                        new
                        {
                            Id = -83,
                            Name = "Окно",
                            RoomId = -17,
                            Type = 4,
                            UserId = "ws17",
                            Value = "closed"
                        },
                        new
                        {
                            Id = -82,
                            Name = "Кондиционер",
                            RoomId = -17,
                            Type = 3,
                            UserId = "ws17",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -81,
                            Name = "Датчик температуры",
                            RoomId = -17,
                            Type = 6,
                            UserId = "ws17",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -89,
                            Name = "Люстра",
                            RoomId = -18,
                            Type = 1,
                            UserId = "ws18",
                            Value = "off"
                        },
                        new
                        {
                            Id = -88,
                            Name = "Окно",
                            RoomId = -18,
                            Type = 4,
                            UserId = "ws18",
                            Value = "closed"
                        },
                        new
                        {
                            Id = -87,
                            Name = "Кондиционер",
                            RoomId = -18,
                            Type = 3,
                            UserId = "ws18",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -86,
                            Name = "Датчик температуры",
                            RoomId = -18,
                            Type = 6,
                            UserId = "ws18",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -94,
                            Name = "Люстра",
                            RoomId = -19,
                            Type = 1,
                            UserId = "ws19",
                            Value = "off"
                        },
                        new
                        {
                            Id = -93,
                            Name = "Окно",
                            RoomId = -19,
                            Type = 4,
                            UserId = "ws19",
                            Value = "closed"
                        },
                        new
                        {
                            Id = -92,
                            Name = "Кондиционер",
                            RoomId = -19,
                            Type = 3,
                            UserId = "ws19",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -91,
                            Name = "Датчик температуры",
                            RoomId = -19,
                            Type = 6,
                            UserId = "ws19",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -99,
                            Name = "Люстра",
                            RoomId = -20,
                            Type = 1,
                            UserId = "ws20",
                            Value = "off"
                        },
                        new
                        {
                            Id = -98,
                            Name = "Окно",
                            RoomId = -20,
                            Type = 4,
                            UserId = "ws20",
                            Value = "closed"
                        },
                        new
                        {
                            Id = -97,
                            Name = "Кондиционер",
                            RoomId = -20,
                            Type = 3,
                            UserId = "ws20",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -96,
                            Name = "Датчик температуры",
                            RoomId = -20,
                            Type = 6,
                            UserId = "ws20",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -104,
                            Name = "Люстра",
                            RoomId = -21,
                            Type = 1,
                            UserId = "demo21",
                            Value = "off"
                        },
                        new
                        {
                            Id = -103,
                            Name = "Окно",
                            RoomId = -21,
                            Type = 4,
                            UserId = "demo21",
                            Value = "closed"
                        },
                        new
                        {
                            Id = -102,
                            Name = "Кондиционер",
                            RoomId = -21,
                            Type = 3,
                            UserId = "demo21",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -101,
                            Name = "Датчик температуры",
                            RoomId = -21,
                            Type = 6,
                            UserId = "demo21",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -109,
                            Name = "Люстра",
                            RoomId = -22,
                            Type = 1,
                            UserId = "demo22",
                            Value = "off"
                        },
                        new
                        {
                            Id = -108,
                            Name = "Окно",
                            RoomId = -22,
                            Type = 4,
                            UserId = "demo22",
                            Value = "closed"
                        },
                        new
                        {
                            Id = -107,
                            Name = "Кондиционер",
                            RoomId = -22,
                            Type = 3,
                            UserId = "demo22",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -106,
                            Name = "Датчик температуры",
                            RoomId = -22,
                            Type = 6,
                            UserId = "demo22",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -114,
                            Name = "Люстра",
                            RoomId = -23,
                            Type = 1,
                            UserId = "demo23",
                            Value = "off"
                        },
                        new
                        {
                            Id = -113,
                            Name = "Окно",
                            RoomId = -23,
                            Type = 4,
                            UserId = "demo23",
                            Value = "closed"
                        },
                        new
                        {
                            Id = -112,
                            Name = "Кондиционер",
                            RoomId = -23,
                            Type = 3,
                            UserId = "demo23",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -111,
                            Name = "Датчик температуры",
                            RoomId = -23,
                            Type = 6,
                            UserId = "demo23",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -119,
                            Name = "Люстра",
                            RoomId = -24,
                            Type = 1,
                            UserId = "demo24",
                            Value = "off"
                        },
                        new
                        {
                            Id = -118,
                            Name = "Окно",
                            RoomId = -24,
                            Type = 4,
                            UserId = "demo24",
                            Value = "closed"
                        },
                        new
                        {
                            Id = -117,
                            Name = "Кондиционер",
                            RoomId = -24,
                            Type = 3,
                            UserId = "demo24",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -116,
                            Name = "Датчик температуры",
                            RoomId = -24,
                            Type = 6,
                            UserId = "demo24",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -124,
                            Name = "Люстра",
                            RoomId = -25,
                            Type = 1,
                            UserId = "demo25",
                            Value = "off"
                        },
                        new
                        {
                            Id = -123,
                            Name = "Окно",
                            RoomId = -25,
                            Type = 4,
                            UserId = "demo25",
                            Value = "closed"
                        },
                        new
                        {
                            Id = -122,
                            Name = "Кондиционер",
                            RoomId = -25,
                            Type = 3,
                            UserId = "demo25",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -121,
                            Name = "Датчик температуры",
                            RoomId = -25,
                            Type = 6,
                            UserId = "demo25",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -129,
                            Name = "Люстра",
                            RoomId = -26,
                            Type = 1,
                            UserId = "demo26",
                            Value = "off"
                        },
                        new
                        {
                            Id = -128,
                            Name = "Окно",
                            RoomId = -26,
                            Type = 4,
                            UserId = "demo26",
                            Value = "closed"
                        },
                        new
                        {
                            Id = -127,
                            Name = "Кондиционер",
                            RoomId = -26,
                            Type = 3,
                            UserId = "demo26",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -126,
                            Name = "Датчик температуры",
                            RoomId = -26,
                            Type = 6,
                            UserId = "demo26",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -134,
                            Name = "Люстра",
                            RoomId = -27,
                            Type = 1,
                            UserId = "demo27",
                            Value = "off"
                        },
                        new
                        {
                            Id = -133,
                            Name = "Окно",
                            RoomId = -27,
                            Type = 4,
                            UserId = "demo27",
                            Value = "closed"
                        },
                        new
                        {
                            Id = -132,
                            Name = "Кондиционер",
                            RoomId = -27,
                            Type = 3,
                            UserId = "demo27",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -131,
                            Name = "Датчик температуры",
                            RoomId = -27,
                            Type = 6,
                            UserId = "demo27",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -139,
                            Name = "Люстра",
                            RoomId = -28,
                            Type = 1,
                            UserId = "demo28",
                            Value = "off"
                        },
                        new
                        {
                            Id = -138,
                            Name = "Окно",
                            RoomId = -28,
                            Type = 4,
                            UserId = "demo28",
                            Value = "closed"
                        },
                        new
                        {
                            Id = -137,
                            Name = "Кондиционер",
                            RoomId = -28,
                            Type = 3,
                            UserId = "demo28",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -136,
                            Name = "Датчик температуры",
                            RoomId = -28,
                            Type = 6,
                            UserId = "demo28",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -144,
                            Name = "Люстра",
                            RoomId = -29,
                            Type = 1,
                            UserId = "demo29",
                            Value = "off"
                        },
                        new
                        {
                            Id = -143,
                            Name = "Окно",
                            RoomId = -29,
                            Type = 4,
                            UserId = "demo29",
                            Value = "closed"
                        },
                        new
                        {
                            Id = -142,
                            Name = "Кондиционер",
                            RoomId = -29,
                            Type = 3,
                            UserId = "demo29",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -141,
                            Name = "Датчик температуры",
                            RoomId = -29,
                            Type = 6,
                            UserId = "demo29",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -149,
                            Name = "Люстра",
                            RoomId = -30,
                            Type = 1,
                            UserId = "demo30",
                            Value = "off"
                        },
                        new
                        {
                            Id = -148,
                            Name = "Окно",
                            RoomId = -30,
                            Type = 4,
                            UserId = "demo30",
                            Value = "closed"
                        },
                        new
                        {
                            Id = -147,
                            Name = "Кондиционер",
                            RoomId = -30,
                            Type = 3,
                            UserId = "demo30",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -146,
                            Name = "Датчик температуры",
                            RoomId = -30,
                            Type = 6,
                            UserId = "demo30",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -154,
                            Name = "Люстра",
                            RoomId = -31,
                            Type = 1,
                            UserId = "demo31",
                            Value = "off"
                        },
                        new
                        {
                            Id = -153,
                            Name = "Окно",
                            RoomId = -31,
                            Type = 4,
                            UserId = "demo31",
                            Value = "closed"
                        },
                        new
                        {
                            Id = -152,
                            Name = "Кондиционер",
                            RoomId = -31,
                            Type = 3,
                            UserId = "demo31",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -151,
                            Name = "Датчик температуры",
                            RoomId = -31,
                            Type = 6,
                            UserId = "demo31",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -159,
                            Name = "Люстра",
                            RoomId = -32,
                            Type = 1,
                            UserId = "demo32",
                            Value = "off"
                        },
                        new
                        {
                            Id = -158,
                            Name = "Окно",
                            RoomId = -32,
                            Type = 4,
                            UserId = "demo32",
                            Value = "closed"
                        },
                        new
                        {
                            Id = -157,
                            Name = "Кондиционер",
                            RoomId = -32,
                            Type = 3,
                            UserId = "demo32",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -156,
                            Name = "Датчик температуры",
                            RoomId = -32,
                            Type = 6,
                            UserId = "demo32",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -164,
                            Name = "Люстра",
                            RoomId = -33,
                            Type = 1,
                            UserId = "demo33",
                            Value = "off"
                        },
                        new
                        {
                            Id = -163,
                            Name = "Окно",
                            RoomId = -33,
                            Type = 4,
                            UserId = "demo33",
                            Value = "closed"
                        },
                        new
                        {
                            Id = -162,
                            Name = "Кондиционер",
                            RoomId = -33,
                            Type = 3,
                            UserId = "demo33",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -161,
                            Name = "Датчик температуры",
                            RoomId = -33,
                            Type = 6,
                            UserId = "demo33",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -169,
                            Name = "Люстра",
                            RoomId = -34,
                            Type = 1,
                            UserId = "demo34",
                            Value = "off"
                        },
                        new
                        {
                            Id = -168,
                            Name = "Окно",
                            RoomId = -34,
                            Type = 4,
                            UserId = "demo34",
                            Value = "closed"
                        },
                        new
                        {
                            Id = -167,
                            Name = "Кондиционер",
                            RoomId = -34,
                            Type = 3,
                            UserId = "demo34",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -166,
                            Name = "Датчик температуры",
                            RoomId = -34,
                            Type = 6,
                            UserId = "demo34",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -174,
                            Name = "Люстра",
                            RoomId = -35,
                            Type = 1,
                            UserId = "demo35",
                            Value = "off"
                        },
                        new
                        {
                            Id = -173,
                            Name = "Окно",
                            RoomId = -35,
                            Type = 4,
                            UserId = "demo35",
                            Value = "closed"
                        },
                        new
                        {
                            Id = -172,
                            Name = "Кондиционер",
                            RoomId = -35,
                            Type = 3,
                            UserId = "demo35",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -171,
                            Name = "Датчик температуры",
                            RoomId = -35,
                            Type = 6,
                            UserId = "demo35",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -179,
                            Name = "Люстра",
                            RoomId = -36,
                            Type = 1,
                            UserId = "demo36",
                            Value = "off"
                        },
                        new
                        {
                            Id = -178,
                            Name = "Окно",
                            RoomId = -36,
                            Type = 4,
                            UserId = "demo36",
                            Value = "closed"
                        },
                        new
                        {
                            Id = -177,
                            Name = "Кондиционер",
                            RoomId = -36,
                            Type = 3,
                            UserId = "demo36",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -176,
                            Name = "Датчик температуры",
                            RoomId = -36,
                            Type = 6,
                            UserId = "demo36",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -184,
                            Name = "Люстра",
                            RoomId = -37,
                            Type = 1,
                            UserId = "demo37",
                            Value = "off"
                        },
                        new
                        {
                            Id = -183,
                            Name = "Окно",
                            RoomId = -37,
                            Type = 4,
                            UserId = "demo37",
                            Value = "closed"
                        },
                        new
                        {
                            Id = -182,
                            Name = "Кондиционер",
                            RoomId = -37,
                            Type = 3,
                            UserId = "demo37",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -181,
                            Name = "Датчик температуры",
                            RoomId = -37,
                            Type = 6,
                            UserId = "demo37",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -189,
                            Name = "Люстра",
                            RoomId = -38,
                            Type = 1,
                            UserId = "demo38",
                            Value = "off"
                        },
                        new
                        {
                            Id = -188,
                            Name = "Окно",
                            RoomId = -38,
                            Type = 4,
                            UserId = "demo38",
                            Value = "closed"
                        },
                        new
                        {
                            Id = -187,
                            Name = "Кондиционер",
                            RoomId = -38,
                            Type = 3,
                            UserId = "demo38",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -186,
                            Name = "Датчик температуры",
                            RoomId = -38,
                            Type = 6,
                            UserId = "demo38",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -194,
                            Name = "Люстра",
                            RoomId = -39,
                            Type = 1,
                            UserId = "demo39",
                            Value = "off"
                        },
                        new
                        {
                            Id = -193,
                            Name = "Окно",
                            RoomId = -39,
                            Type = 4,
                            UserId = "demo39",
                            Value = "closed"
                        },
                        new
                        {
                            Id = -192,
                            Name = "Кондиционер",
                            RoomId = -39,
                            Type = 3,
                            UserId = "demo39",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -191,
                            Name = "Датчик температуры",
                            RoomId = -39,
                            Type = 6,
                            UserId = "demo39",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -199,
                            Name = "Люстра",
                            RoomId = -40,
                            Type = 1,
                            UserId = "demo40",
                            Value = "off"
                        },
                        new
                        {
                            Id = -198,
                            Name = "Окно",
                            RoomId = -40,
                            Type = 4,
                            UserId = "demo40",
                            Value = "closed"
                        },
                        new
                        {
                            Id = -197,
                            Name = "Кондиционер",
                            RoomId = -40,
                            Type = 3,
                            UserId = "demo40",
                            Value = "+20"
                        },
                        new
                        {
                            Id = -196,
                            Name = "Датчик температуры",
                            RoomId = -40,
                            Type = 6,
                            UserId = "demo40",
                            Value = "+20"
                        });
                });

            modelBuilder.Entity("WorldSkillsSmartUniversityApi.Models.Domain.Macro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int?>("UserId")
                        .IsRequired();

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.HasIndex("Username");

                    b.ToTable("Macros");
                });

            modelBuilder.Entity("WorldSkillsSmartUniversityApi.Models.Domain.MacroDevice", b =>
                {
                    b.Property<int>("MacroId");

                    b.Property<int>("DeviceId");

                    b.Property<string>("Value");

                    b.HasKey("MacroId", "DeviceId");

                    b.HasIndex("DeviceId");

                    b.ToTable("MacroDevice");
                });

            modelBuilder.Entity("WorldSkillsSmartUniversityApi.Models.Domain.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Photo");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Name = "Г-511",
                            Photo = "image.png",
                            UserId = "ws1"
                        },
                        new
                        {
                            Id = -2,
                            Name = "Г-511",
                            Photo = "image.png",
                            UserId = "ws2"
                        },
                        new
                        {
                            Id = -3,
                            Name = "Г-511",
                            Photo = "image.png",
                            UserId = "ws3"
                        },
                        new
                        {
                            Id = -4,
                            Name = "Г-511",
                            Photo = "image.png",
                            UserId = "ws4"
                        },
                        new
                        {
                            Id = -5,
                            Name = "Г-511",
                            Photo = "image.png",
                            UserId = "ws5"
                        },
                        new
                        {
                            Id = -6,
                            Name = "Г-511",
                            Photo = "image.png",
                            UserId = "ws6"
                        },
                        new
                        {
                            Id = -7,
                            Name = "Г-511",
                            Photo = "image.png",
                            UserId = "ws7"
                        },
                        new
                        {
                            Id = -8,
                            Name = "Г-511",
                            Photo = "image.png",
                            UserId = "ws8"
                        },
                        new
                        {
                            Id = -9,
                            Name = "Г-511",
                            Photo = "image.png",
                            UserId = "ws9"
                        },
                        new
                        {
                            Id = -10,
                            Name = "Г-511",
                            Photo = "image.png",
                            UserId = "ws10"
                        },
                        new
                        {
                            Id = -11,
                            Name = "Г-511",
                            Photo = "image.png",
                            UserId = "ws11"
                        },
                        new
                        {
                            Id = -12,
                            Name = "Г-511",
                            Photo = "image.png",
                            UserId = "ws12"
                        },
                        new
                        {
                            Id = -13,
                            Name = "Г-511",
                            Photo = "image.png",
                            UserId = "ws13"
                        },
                        new
                        {
                            Id = -14,
                            Name = "Г-511",
                            Photo = "image.png",
                            UserId = "ws14"
                        },
                        new
                        {
                            Id = -15,
                            Name = "Г-511",
                            Photo = "image.png",
                            UserId = "ws15"
                        },
                        new
                        {
                            Id = -16,
                            Name = "Г-511",
                            Photo = "image.png",
                            UserId = "ws16"
                        },
                        new
                        {
                            Id = -17,
                            Name = "Г-511",
                            Photo = "image.png",
                            UserId = "ws17"
                        },
                        new
                        {
                            Id = -18,
                            Name = "Г-511",
                            Photo = "image.png",
                            UserId = "ws18"
                        },
                        new
                        {
                            Id = -19,
                            Name = "Г-511",
                            Photo = "image.png",
                            UserId = "ws19"
                        },
                        new
                        {
                            Id = -20,
                            Name = "Г-511",
                            Photo = "image.png",
                            UserId = "ws20"
                        },
                        new
                        {
                            Id = -21,
                            Name = "Г-511",
                            Photo = "image.png",
                            UserId = "demo21"
                        },
                        new
                        {
                            Id = -22,
                            Name = "Г-511",
                            Photo = "image.png",
                            UserId = "demo22"
                        },
                        new
                        {
                            Id = -23,
                            Name = "Г-511",
                            Photo = "image.png",
                            UserId = "demo23"
                        },
                        new
                        {
                            Id = -24,
                            Name = "Г-511",
                            Photo = "image.png",
                            UserId = "demo24"
                        },
                        new
                        {
                            Id = -25,
                            Name = "Г-511",
                            Photo = "image.png",
                            UserId = "demo25"
                        },
                        new
                        {
                            Id = -26,
                            Name = "Г-511",
                            Photo = "image.png",
                            UserId = "demo26"
                        },
                        new
                        {
                            Id = -27,
                            Name = "Г-511",
                            Photo = "image.png",
                            UserId = "demo27"
                        },
                        new
                        {
                            Id = -28,
                            Name = "Г-511",
                            Photo = "image.png",
                            UserId = "demo28"
                        },
                        new
                        {
                            Id = -29,
                            Name = "Г-511",
                            Photo = "image.png",
                            UserId = "demo29"
                        },
                        new
                        {
                            Id = -30,
                            Name = "Г-511",
                            Photo = "image.png",
                            UserId = "demo30"
                        },
                        new
                        {
                            Id = -31,
                            Name = "Г-511",
                            Photo = "image.png",
                            UserId = "demo31"
                        },
                        new
                        {
                            Id = -32,
                            Name = "Г-511",
                            Photo = "image.png",
                            UserId = "demo32"
                        },
                        new
                        {
                            Id = -33,
                            Name = "Г-511",
                            Photo = "image.png",
                            UserId = "demo33"
                        },
                        new
                        {
                            Id = -34,
                            Name = "Г-511",
                            Photo = "image.png",
                            UserId = "demo34"
                        },
                        new
                        {
                            Id = -35,
                            Name = "Г-511",
                            Photo = "image.png",
                            UserId = "demo35"
                        },
                        new
                        {
                            Id = -36,
                            Name = "Г-511",
                            Photo = "image.png",
                            UserId = "demo36"
                        },
                        new
                        {
                            Id = -37,
                            Name = "Г-511",
                            Photo = "image.png",
                            UserId = "demo37"
                        },
                        new
                        {
                            Id = -38,
                            Name = "Г-511",
                            Photo = "image.png",
                            UserId = "demo38"
                        },
                        new
                        {
                            Id = -39,
                            Name = "Г-511",
                            Photo = "image.png",
                            UserId = "demo39"
                        },
                        new
                        {
                            Id = -40,
                            Name = "Г-511",
                            Photo = "image.png",
                            UserId = "demo40"
                        });
                });

            modelBuilder.Entity("WorldSkillsSmartUniversityApi.Models.Domain.User", b =>
                {
                    b.Property<string>("Username")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Password");

                    b.HasKey("Username");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Username = "ws1",
                            Password = "028c08"
                        },
                        new
                        {
                            Username = "ws2",
                            Password = "b1f6f3"
                        },
                        new
                        {
                            Username = "ws3",
                            Password = "0ad676"
                        },
                        new
                        {
                            Username = "ws4",
                            Password = "23417c"
                        },
                        new
                        {
                            Username = "ws5",
                            Password = "3c1575"
                        },
                        new
                        {
                            Username = "ws6",
                            Password = "a935cb"
                        },
                        new
                        {
                            Username = "ws7",
                            Password = "0167ad"
                        },
                        new
                        {
                            Username = "ws8",
                            Password = "d21d6a"
                        },
                        new
                        {
                            Username = "ws9",
                            Password = "b3d3a1"
                        },
                        new
                        {
                            Username = "ws10",
                            Password = "91df37"
                        },
                        new
                        {
                            Username = "ws11",
                            Password = "6668b5"
                        },
                        new
                        {
                            Username = "ws12",
                            Password = "b5325f"
                        },
                        new
                        {
                            Username = "ws13",
                            Password = "9791c5"
                        },
                        new
                        {
                            Username = "ws14",
                            Password = "f51c62"
                        },
                        new
                        {
                            Username = "ws15",
                            Password = "fd7240"
                        },
                        new
                        {
                            Username = "ws16",
                            Password = "105703"
                        },
                        new
                        {
                            Username = "ws17",
                            Password = "c24921"
                        },
                        new
                        {
                            Username = "ws18",
                            Password = "97b28b"
                        },
                        new
                        {
                            Username = "ws19",
                            Password = "7431ee"
                        },
                        new
                        {
                            Username = "ws20",
                            Password = "94a18a"
                        },
                        new
                        {
                            Username = "demo21",
                            Password = "2a3a75"
                        },
                        new
                        {
                            Username = "demo22",
                            Password = "baa2c9"
                        },
                        new
                        {
                            Username = "demo23",
                            Password = "a78423"
                        },
                        new
                        {
                            Username = "demo24",
                            Password = "436f22"
                        },
                        new
                        {
                            Username = "demo25",
                            Password = "351e5c"
                        },
                        new
                        {
                            Username = "demo26",
                            Password = "54f71e"
                        },
                        new
                        {
                            Username = "demo27",
                            Password = "285d66"
                        },
                        new
                        {
                            Username = "demo28",
                            Password = "a5ad3b"
                        },
                        new
                        {
                            Username = "demo29",
                            Password = "e63dfb"
                        },
                        new
                        {
                            Username = "demo30",
                            Password = "11fa98"
                        },
                        new
                        {
                            Username = "demo31",
                            Password = "6d2b24"
                        },
                        new
                        {
                            Username = "demo32",
                            Password = "ce9234"
                        },
                        new
                        {
                            Username = "demo33",
                            Password = "384007"
                        },
                        new
                        {
                            Username = "demo34",
                            Password = "fb5128"
                        },
                        new
                        {
                            Username = "demo35",
                            Password = "70cfaf"
                        },
                        new
                        {
                            Username = "demo36",
                            Password = "c9c9dc"
                        },
                        new
                        {
                            Username = "demo37",
                            Password = "89b597"
                        },
                        new
                        {
                            Username = "demo38",
                            Password = "95c551"
                        },
                        new
                        {
                            Username = "demo39",
                            Password = "254202"
                        },
                        new
                        {
                            Username = "demo40",
                            Password = "b92680"
                        });
                });

            modelBuilder.Entity("WorldSkillsSmartUniversityApi.Models.Domain.Device", b =>
                {
                    b.HasOne("WorldSkillsSmartUniversityApi.Models.Domain.Room", "Room")
                        .WithMany("Devices")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WorldSkillsSmartUniversityApi.Models.Domain.User", "User")
                        .WithMany("Devices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WorldSkillsSmartUniversityApi.Models.Domain.Macro", b =>
                {
                    b.HasOne("WorldSkillsSmartUniversityApi.Models.Domain.User", "User")
                        .WithMany("Macros")
                        .HasForeignKey("Username");
                });

            modelBuilder.Entity("WorldSkillsSmartUniversityApi.Models.Domain.MacroDevice", b =>
                {
                    b.HasOne("WorldSkillsSmartUniversityApi.Models.Domain.Device", "Device")
                        .WithMany("Macros")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WorldSkillsSmartUniversityApi.Models.Domain.Macro", "Macro")
                        .WithMany("Devices")
                        .HasForeignKey("MacroId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WorldSkillsSmartUniversityApi.Models.Domain.Room", b =>
                {
                    b.HasOne("WorldSkillsSmartUniversityApi.Models.Domain.User", "User")
                        .WithMany("Rooms")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
