// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorldSkillsSmartUniversityApi.Models.Domain;

namespace WorldSkillsSmartUniversityApi.Migrations
{
    [DbContext(typeof(SmartUniversityDbContext))]
    [Migration("20190303225129_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034");

            modelBuilder.Entity("WorldSkillsSmartUniversityApi.Models.Domain.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("RoomId");

                    b.Property<int>("TypeId");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("TypeId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("WorldSkillsSmartUniversityApi.Models.Domain.DeviceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("DeviceType");
                });

            modelBuilder.Entity("WorldSkillsSmartUniversityApi.Models.Domain.Macro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Macros");
                });

            modelBuilder.Entity("WorldSkillsSmartUniversityApi.Models.Domain.MacroDevice", b =>
                {
                    b.Property<int>("MacroId");

                    b.Property<int>("DeviceId");

                    b.Property<string>("Value");

                    b.HasKey("MacroId", "DeviceId");

                    b.HasIndex("DeviceId");

                    b.ToTable("MacroDevice");
                });

            modelBuilder.Entity("WorldSkillsSmartUniversityApi.Models.Domain.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Photo");

                    b.HasKey("Id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("WorldSkillsSmartUniversityApi.Models.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Password");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WorldSkillsSmartUniversityApi.Models.Domain.Device", b =>
                {
                    b.HasOne("WorldSkillsSmartUniversityApi.Models.Domain.Room", "Room")
                        .WithMany("Devices")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WorldSkillsSmartUniversityApi.Models.Domain.DeviceType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WorldSkillsSmartUniversityApi.Models.Domain.MacroDevice", b =>
                {
                    b.HasOne("WorldSkillsSmartUniversityApi.Models.Domain.Device", "Device")
                        .WithMany("Macros")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WorldSkillsSmartUniversityApi.Models.Domain.Macro", "Macro")
                        .WithMany("Devices")
                        .HasForeignKey("MacroId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
